# SPDX-FileCopyrightText: 2022 Deren Vural
# SPDX-License-Identifier: GPL-3.0-or-later

# These are supported funding model platforms

github: derenv # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: lokonu # Replace with a single Ko-fi username
